export { OnboardingPage } from './OnboardingPage';
export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { HomePage } from './HomePage';
export { DiscoverPage } from './DiscoverPage';
export { NotificationsPage } from './NotificationsPage';
export { ProfilePage } from './ProfilePage';
export { PostPage } from './PostPage';
export { RecommendationDetailPage } from './RecommendationDetailPage';